---
#  Copyright (c) 2025. Andrew M. Zhang All rights reserved.
#  This work is protected by copyright law and international treaties. No part of this work may be copied, reproduced,
#  distributed, transmitted, stored in a retrieval system, or translated into any language, in any form or by any means,
#  without the prior written permission of the copyright holder. Unauthorized use, duplication, or distribution is
#  strictly prohibited and may result in civil and/or criminal penalties. For inquiries regarding licensing, usage,
#  or permissions, please open an issue on this repository: https://github.com/AndyWebServices/ansible-roles/issues

- name: Ensure remote docker-compose directory exists
  ansible.builtin.file:
    path: "{{ swag_remote_repo_path }}/composes/{{ _config.container_name }}-docker"
    state: directory
    mode: '0755'
