---
swag_docker_container_name: swag
swag_docker_tz: "{{ tz | default('UTC') }}"
swag_docker_validation: "{{ validation | default('') }}"
swag_docker_subdomains: "{{ subdomains | default([]) }}"
swag_docker_certprovider: "{{ certprovider | default('') }}"
swag_docker_dnsplugin: "{{ dnsplugin | default('') }}"
swag_docker_email: "{{ email | default('') }}"
swag_docker_only_subdomains: "{{ only_subdomains | default(false) }}"
swag_docker_extra_domains: "{{ extra_domains | default([]) }}"
swag_docker_ports: "{{ ports | default([]) }}"
swag_docker_docker_network: "{{ docker_network | default('') }}"
swag_docker_check_docker: "{{ check_docker | default(true) }}"
swag_docker_start_container: "{{ start_container | default(true) }}"
