---
role_name_check: 1
dependency:
  name: galaxy

driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    cgroupns_mode: host
    privileged: true

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "$HOME/.ansible/roles/:$MOLECULE_PROJECT_DIRECTORY/.."
